/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

dependencies {
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
    api("org.springframework.boot:spring-boot-starter-web:3.2.3")
    // https://mvnrepository.com/artifact/org.springframework.data/spring-data-commons
    api("org.springframework.data:spring-data-commons:3.2.4")
// https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui
    api("org.springdoc:springdoc-openapi-ui:1.8.0")
// https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
    api("com.google.code.findbugs:jsr305:3.0.2")
// https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.0")
// https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0")
// https://mvnrepository.com/artifact/org.openapitools/jackson-databind-nullable
    api("org.openapitools:jackson-databind-nullable:0.2.6")
// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
    api("org.springframework.boot:spring-boot-starter-validation:3.2.3")
// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    api("com.fasterxml.jackson.core:jackson-databind:2.17.0")
// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.2.3")

}

group = "org.openapitools"
version = "1.0.0"
description = "openapi-spring"

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
