openapi: 3.0.0
info:
  description: >-
    cf-rating-service API.
  version: 1.0.0
  title: OpenAPI cf-rating-service
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: user
    description: User API
paths:
  /ratings:
    get:
      tags:
        - rating
      summary: Get users rating
      description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/RatingsResponse'

components:
  schemas:
    RatingsResponse:
      type: object
      properties:
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/Rating'
    Rating:
      type: object
      required:
        - value
      properties:
        value:
          type: integer
