/**
 * OpenAPI cf-rating-service
 * cf-rating-service API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RatingsResponse from '../model/RatingsResponse';

/**
* Rating service.
* @module api/RatingApi
* @version 1.0.0
*/
export default class RatingApi {

    /**
    * Constructs a new RatingApi. 
    * @alias module:api/RatingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the ratingsGet operation.
     * @callback module:api/RatingApi~ratingsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RatingsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get users rating
     * 
     * @param {module:api/RatingApi~ratingsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RatingsResponse}
     */
    ratingsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RatingsResponse;
      return this.apiClient.callApi(
        '/ratings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
